language: generic

env:
  global:
    - ENCRYPTION_LABEL="82f6fcb5a224"
    - DEPLOY_USER="annevankesteren"

script:
  - curl --remote-name https://resources.whatwg.org/build/deploy.sh && bash ./deploy.sh

notifications:
  email:
    on_success: never
    on_failure: always
